const toggle=document.querySelector('#vpn-toggle'),autoButton=document.querySelector('#auto-mode'),pingButton=document.querySelector('#ping'),servers=[...document.querySelectorAll('.server')],status=document.querySelector('#demo-status'),modeStatus=document.querySelector('#mode-status'),connection=document.querySelector('.connection'),progress=document.querySelector('#scan-progress');
let enabled=true,automatic=true,paused=false,visible=false,busy=false,selected=0,round=0,seconds=30,generation=0;
const samples=[[62,48,35],[39,null,58],[64,32,46]];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function renderMode(){autoButton.classList.toggle('active',automatic);autoButton.setAttribute('aria-pressed',String(automatic));autoButton.querySelector('i').textContent='';modeStatus.textContent=automatic?(paused?'Автодемонстрация на паузе':`Следующая проверка через ${seconds} сек.`):'Ручной режим · локация зафиксирована';progress.style.width=automatic?`${(30-seconds)/30*100}%`:'0%';}
function highlight(index){selected=index;servers.forEach((el,i)=>{el.classList.toggle('selected',i===index);el.setAttribute('aria-pressed',String(i===index));el.querySelector('i').textContent='';});document.querySelector('#current-location').textContent=servers[index].dataset.location;}
function stopScan(){generation++;busy=false;pingButton.disabled=false;pingButton.textContent='Проверить пинг';servers.forEach(el=>{el.classList.remove('scanning');if(el.querySelector('.latency').textContent==='…')el.querySelector('.latency').textContent='—';});connection.classList.remove('switching');document.querySelector('#vpn-state').textContent=enabled?'VPN подключён':'VPN отключён';}
async function scan(){if(busy||!enabled)return;busy=true;const token=++generation;const values=samples[round++%samples.length];pingButton.disabled=true;pingButton.textContent='Проверяем…';status.textContent='Проверяем доступность и пинг серверов…';progress.style.width='100%';servers.forEach(el=>{el.classList.remove('unavailable');el.querySelector('.latency').textContent='…';});for(let i=0;i<servers.length;i++){servers[i].classList.add('scanning');await delay(650);if(token!==generation)return;servers[i].classList.remove('scanning');servers[i].classList.toggle('unavailable',values[i]===null);servers[i].querySelector('.latency').textContent=values[i]===null?'Недоступен':`${values[i]} мс`;}
if(automatic){const best=values.reduce((a,v,i)=>v!==null&&(a===-1||v<values[a])?i:a,-1);if(best!==selected){connection.classList.add('switching');document.querySelector('#vpn-state').textContent='Переключаем локацию…';status.textContent='Выбираем доступный сервер с наименьшим пингом…';await delay(700);if(token!==generation)return;highlight(best);connection.classList.remove('switching');document.querySelector('#vpn-state').textContent='VPN подключён';}status.textContent=`Пример: лучший отклик — ${servers[best].dataset.location.split(' · ')[0]}, ${values[best]} мс.`;}else{status.textContent='Пинг проверен. Выбранная вручную локация остаётся прежней.';}
busy=false;seconds=30;pingButton.disabled=false;pingButton.textContent='Проверить пинг';renderMode();}
toggle.addEventListener('click',()=>{stopScan();enabled=!enabled;toggle.setAttribute('aria-pressed',String(enabled));connection.classList.toggle('disabled',!enabled);document.querySelector('#vpn-state').textContent=enabled?'VPN подключён':'VPN отключён';status.textContent=enabled?'Демонстрация: VPN включён.':'Демонстрация: VPN выключен.';seconds=30;renderMode();if(enabled&&automatic&&!paused)scan();});
servers.forEach((button,i)=>button.addEventListener('click',()=>{stopScan();automatic=false;highlight(i);renderMode();status.textContent='Ручной выбор: локация зафиксирована. Автопереключение отключено.';}));
autoButton.addEventListener('click',()=>{stopScan();automatic=true;seconds=30;renderMode();status.textContent='Автоматический режим: роутер выбирает лучший доступный сервер.';scan();});
pingButton.addEventListener('click',scan);document.querySelector('#demo-replay').addEventListener('click',scan);document.querySelector('#demo-pause').addEventListener('click',()=>{paused=!paused;if(paused)stopScan();const b=document.querySelector('#demo-pause');b.setAttribute('aria-pressed',String(paused));b.textContent=paused?'Продолжить анимацию':'Пауза анимации';renderMode();if(!paused&&automatic&&enabled)scan();});
document.querySelector('#diagnose').addEventListener('click',()=>{status.textContent=enabled?'Пример диагностики: роутер доступен, VPN подключён.':'Пример диагностики: роутер доступен, VPN выключен.';});
const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible&&round===0&&!paused&&automatic&&enabled)scan();},{threshold:.35});observer.observe(document.querySelector('.phone'));
setInterval(()=>{if(!visible||document.hidden||paused||!automatic||!enabled||busy)return;seconds--;renderMode();if(seconds<=0)scan();},1000);renderMode();
const dialog=document.querySelector('#selection');document.querySelectorAll('.model-choice').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#selected-model').textContent=button.dataset.model;document.querySelector("#selected-price").textContent=button.dataset.price;dialog.showModal();}));document.querySelectorAll('.close,.close-dialog').forEach(button=>button.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});

const themeButton=document.querySelector('#theme-toggle');function updateThemeButton(){const light=document.documentElement.dataset.theme==='light';themeButton.setAttribute('aria-pressed',String(light));themeButton.setAttribute('aria-label',light?'Включить тёмную тему':'Включить светлую тему');themeButton.querySelector('.theme-label').textContent=light?'Тёмная тема':'Светлая тема';}updateThemeButton();themeButton.addEventListener('click',()=>{const light=document.documentElement.dataset.theme!=='light';document.documentElement.dataset.theme=light?'light':'dark';try{localStorage.setItem('nextrouter-theme',light?'light':'dark');}catch(e){}updateThemeButton();});

// Motion enhances the content without hiding it when scripts are unavailable.
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const revealElements=document.querySelectorAll('.hero-copy,.hero-visual,.section-heading,.benefit,.app-copy,.demo-area,.model,.gift-grid article,.regional-benefits article,.faq-section,.final-cta');
const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){if(!reducedMotion.matches)entry.target.classList.add('entered');revealObserver.unobserve(entry.target);}});},{threshold:.1});revealElements.forEach((el,i)=>{el.style.setProperty('--enter-delay',`${Math.min(i%4,3)*60}ms`);revealObserver.observe(el);});
const menuButton=document.querySelector('#menu-toggle'),siteNav=document.querySelector('#site-nav');function closeMenu(){siteNav.classList.remove('nav-open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Открыть меню');}menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');siteNav.classList.toggle('nav-open',open);});siteNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});window.addEventListener('resize',()=>{if(window.innerWidth>=768)closeMenu();});
const topButton=document.querySelector('#back-top'),readingProgress=document.querySelector('#reading-progress');let scrollScheduled=false;function updateScroll(){const total=document.documentElement.scrollHeight-window.innerHeight;readingProgress.style.transform=`scaleX(${total>0?Math.min(1,window.scrollY/total):0})`;topButton.hidden=window.scrollY<600;scrollScheduled=false;}window.addEventListener('scroll',()=>{if(!scrollScheduled){scrollScheduled=true;requestAnimationFrame(updateScroll);}},{passive:true});window.addEventListener('resize',updateScroll);updateScroll();topButton.addEventListener('click',()=>window.scrollTo({top:0,behavior:reducedMotion.matches?'instant':'smooth'}));
const navObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){siteNav.querySelectorAll('a').forEach(a=>{const active=a.getAttribute('href')==='#'+entry.target.id;a.classList.toggle('current-section',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}});},{rootMargin:'-10% 0px -55% 0px',threshold:0});document.querySelectorAll('main section[id]').forEach(section=>navObserver.observe(section));
const visual=document.querySelector('.hero-visual');visual.addEventListener('pointermove',e=>{if(reducedMotion.matches||e.pointerType!=='mouse'||window.innerWidth<1024)return;const r=visual.getBoundingClientRect();visual.style.setProperty('--tilt-x',`${-(e.clientY-r.top-r.height/2)/r.height*3}deg`);visual.style.setProperty('--tilt-y',`${(e.clientX-r.left-r.width/2)/r.width*3}deg`);});visual.addEventListener('pointerleave',()=>{visual.style.setProperty('--tilt-x','0deg');visual.style.setProperty('--tilt-y','0deg');});

const guideButtons=[...document.querySelectorAll('[data-suggest]')];guideButtons.forEach(button=>{button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{guideButtons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.model').forEach(card=>card.classList.toggle('suggested',card.querySelector('[data-model]').dataset.model===button.dataset.suggest));document.querySelector('#model-guide-result').textContent=button.dataset.suggest==='Netis NX31'?'Вам подойдёт NX31: Wi‑Fi 6 AX3000, без USB. Цена — 15 000 ₽.':'Вам подойдёт N6v2: USB 3.0 и Wi‑Fi 6 AX1800. Цена — 15 000 ₽.';const card=[...document.querySelectorAll('.model')].find(card=>card.classList.contains('suggested'));card.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'center'});});});
const modelVisibility=new IntersectionObserver(entries=>document.body.classList.toggle('models-visible',entries[0].isIntersecting),{threshold:0});modelVisibility.observe(document.querySelector('.model-grid'));
